<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-01-14T18:30:02 IST" name="Suite" finished-at="2024-01-14T18:30:24 IST" duration-ms="21610">
    <groups>
      <group name="errorhandling">
        <method signature="ErrorReportOrdercode2.ErrorValidation()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" name="ErrorValidation" class="rahulshettyacademy.test.ErrorReportOrdercode2"/>
      </group> <!-- errorhandling -->
    </groups>
    <test started-at="2024-01-14T18:30:02 IST" name="Report Test" finished-at="2024-01-14T18:30:24 IST" duration-ms="21610">
      <class name="rahulshettyacademy.test.ErrorReportOrdercode2">
        <test-method is-config="true" signature="Launch()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:02 IST" name="Launch" finished-at="2024-01-14T18:30:06 IST" duration-ms="3458" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method signature="submit()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:06 IST" name="submit" finished-at="2024-01-14T18:30:15 IST" duration-ms="9567" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submit -->
        <test-method is-config="true" signature="Treadown()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:15 IST" name="Treadown" finished-at="2024-01-14T18:30:16 IST" duration-ms="87" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Treadown -->
        <test-method is-config="true" signature="Launch()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:16 IST" name="Launch" finished-at="2024-01-14T18:30:18 IST" duration-ms="2165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method retried="true" signature="ErrorValidation()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:18 IST" name="ErrorValidation" finished-at="2024-01-14T18:30:18 IST" duration-ms="397" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email o password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email o password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.test.ErrorReportOrdercode2.ErrorValidation(ErrorReportOrdercode2.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidation -->
        <test-method is-config="true" signature="Treadown()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:18 IST" name="Treadown" finished-at="2024-01-14T18:30:18 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Treadown -->
        <test-method is-config="true" signature="Launch()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:18 IST" name="Launch" finished-at="2024-01-14T18:30:20 IST" duration-ms="1516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method signature="ErrorValidation()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:20 IST" name="ErrorValidation" finished-at="2024-01-14T18:30:20 IST" duration-ms="375" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email o password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email o password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at rahulshettyacademy.test.ErrorReportOrdercode2.ErrorValidation(ErrorReportOrdercode2.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidation -->
        <test-method is-config="true" signature="Treadown()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:20 IST" name="Treadown" finished-at="2024-01-14T18:30:21 IST" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Treadown -->
        <test-method is-config="true" signature="Launch()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:21 IST" name="Launch" finished-at="2024-01-14T18:30:23 IST" duration-ms="2670" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Launch -->
        <test-method signature="OrderPageHistory()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:23 IST" name="OrderPageHistory" finished-at="2024-01-14T18:30:24 IST" depends-on-methods="rahulshettyacademy.test.ErrorReportOrdercode2.submit" duration-ms="656" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderPageHistory -->
        <test-method is-config="true" signature="Treadown()[pri:0, instance:rahulshettyacademy.test.ErrorReportOrdercode2@e044b4a]" started-at="2024-01-14T18:30:24 IST" name="Treadown" finished-at="2024-01-14T18:30:24 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Treadown -->
      </class> <!-- rahulshettyacademy.test.ErrorReportOrdercode2 -->
    </test> <!-- Report Test -->
  </suite> <!-- Suite -->
</testng-results>
